export const dashboardData = {
  assetSummary: {
    totalBalance: "$12,430",
    change: "+3.4%",
    changeLabel: "vs last 7 days",
    activeRange: "7D",
  },
  exchangesSummary: {
    total: "$21,240",
    exchanges: [
      { name: "Binance", value: "$9,150", amount: 9150 },
      { name: "Bybit", value: "$6,050", amount: 6050 },
      { name: "Kraken", value: "$3,150", amount: 3150 },
      { name: "Coinbase", value: "$2,400", amount: 2400 },
      { name: "Others", value: "$490", amount: 490 },
    ],
  },
  alerts: [
    {
      title: "Autotrader Error",
      message: "Insufficient balance for USDT / AVAX",
      type: "Action Needed",
      time: "2 minutes ago",
      cta: "View Autotrader",
      alertState: "error",
      alertStatus: "active",
    },
    {
      title: "Margin Warning",
      message: "Maintenance margin below 20% on BTC / USDT",
      type: "Warning",
      time: "10 minutes ago",
      cta: "Review Margin",
      alertState: "error",
      alertStatus: "active",
    },
    {
      title: "Autotrader Paused",
      message: "Trading paused for ETH / USDT due to volatility",
      type: "Action Needed",
      time: "35 minutes ago",
      cta: "Resume Autotrader",
      alertState: "error",
      alertStatus: "active",
    },
    {
      title: "Deposit Confirmed",
      message: "$1,200 USDT deposit confirmed",
      type: "Update",
      time: "1 hour ago",
      cta: "View Wallet",
      alertState: "error",
      alertStatus: "active",
    },
    {
      title: "Price Alert",
      message: "SOL reached $182.40 target",
      type: "Update",
      time: "3 hours ago",
      cta: "View Chart",
      alertState: "error",
      alertStatus: "active",
    },
    {
      title: "Risk Review Needed",
      message: "One or more positions require review",
      type: "Action Needed",
      time: "Yesterday",
      cta: "Review Positions",
      alertState: "error",
      alertStatus: "active",
    },
  ],
  topAutotraders: [
    {
      name: "alexayu",
      pair: "USDT / AVAX",
      runtime: "Running 12d 4h",
      pnl: "+9.2%",
    },
    {
      name: "testing 3",
      pair: "USDT / BTC",
      runtime: "Running 31d 16h",
      pnl: "+7.8%",
    },
    {
      name: "aklayu",
      pair: "USDT / AVAX",
      runtime: "Running 44d 6h",
      pnl: "+5.5%",
    },
  ],
  tradeHistory: [
    {
      pair: ["avax", "usdt"],
      action: "BUY",
      status: "FILLED",
      profitUsd: "+$124.30",
      profitPct: "+2.1%",
      profitState: "positive",
      time: "2m",
    },
    {
      pair: ["btc", "usdt"],
      action: "SELL",
      status: "FAILED",
      profitUsd: "–",
      profitPct: "–",
      profitState: "neutral",
      time: "18m",
    },
    {
      pair: ["eth", "usdt"],
      action: "SELL",
      status: "FILLED",
      profitUsd: "-$48.90",
      profitPct: "-0.6%",
      profitState: "negative",
      time: "1h",
    },
    {
      pair: ["sol", "usdt"],
      action: "CANCEL",
      status: "CANCELLED",
      profitUsd: "–",
      profitPct: "–",
      profitState: "neutral",
      time: "3h",
    },
    {
      pair: ["ada", "usdt"],
      action: "BUY",
      status: "ERROR",
      profitUsd: "–",
      profitPct: "–",
      profitState: "neutral",
      time: "7h",
    },
    {
      pair: ["btc", "usdt"],
      action: "CANCEL",
      status: "CANCELLED",
      profitUsd: "+$0.00",
      profitPct: "0.0%",
      profitState: "neutral",
      time: "1d",
    },
  ],
};

export const fetchDashboardData = () =>
  new Promise((resolve) => {
    setTimeout(() => {
      resolve(structuredClone(dashboardData));
    }, 700);
  });
